### ISSUE TITLE
locale support

### ISSUE THREAD

**Issue by skybber** [adminfaces/admin-starter#14]
`<f:view locale="..">`  is traditionaly used for multilanguage application. It would be nice if adminfaces has support for it.

Suggestion: use bean localeManager as in https://stackoverflow.com/questions/5388426/jsf-2-0-set-locale-throughout-session-from-browser-and-programmatically

**Comment by rmpestano** [comment]
Hi @skybber,

I think it would be nice to have as an example in admin-starter but I'm against adding it in admin-template because users that don't need multiple locales (most JSF apps) on their application would need to disable multi locale support .

WDYT?  would you like to contribute this example here? I imagine something like the stackoverflow answer.

Thanks for the feedback

**Comment by skybber** [comment]
Unfortunately it's problem to do an example in admin-starter now, since the base template admin-base.xhtml does not use f:view, so it's not possible override default locale on JSF/xhtml level. We're using hacks to change locale before restore view phase now ...

**Comment by rmpestano** [comment]
can't we use f:view in application template? https://github.com/adminfaces/admin-starter/blob/master/src/main/webapp/WEB-INF/templates/template.xhtml

**Comment by skybber** [comment]
You are right! I don't know why I've thought that `f:view` is pair tag enclosing localized JSF subtree. It can be non-pair singleton defined in the header of JSF... Excuse me, I'm closing this.

**Comment by rmpestano** [comment]
No need to excuse, if you need any help don't hesitate to open an issue, it may help others with same doubts in the future.
